_base_: ../../instrument_classification/configs/convnet_scratch.yaml
output_dir: runs/contrastive_learning/finetune_convnet_legacy_moco
model:
  init_checkpoint: runs/contrastive_learning/legacy_moco_convnet/seed0/encoder_last.pt
